spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/ask
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true # 하이버 네이트가 실행한 SQL을 출력한다
        format_sql: true # 하이버 네이트가 실행한 SQL을 출력할 때 보기 쉽게 정렬한다

logging.level:
  org.hibernate.SQL: debug